Adding badge functionality
avbelyshev/test_guru pull request #17
Opened 2018-05-09 15:25 UTC by avbelyshev

2018-05-10 17:09 UTC, iBublik requested changes

2018-05-10 17:09 UTC, iBublik commented on app/addons/badges_receiver.rb
> +    Test.by_category(category).count == @user.tests.where('test_passages.passed = ?', true).by_category(category).count
Проверять все же лучше список id, а не кол-во пройденных тестов. Ведь никто не запрещает проходить один и тот же тест несколько раз
В where лучше использовать хэш - `where(test_passages: { passed: true })`. И можно вынести в скоуп, т.к. ниже такой же запрос используется

2018-05-10 17:09 UTC, iBublik commented on app/addons/badges_receiver.rb
> +    @user.tests.where(id: @test_passage.test_id).count == attempts.to_i
Мне кажется, параметр тут не особо нужен. Все-таки правило `first_attempt?` имеет говорящее название :)

2018-05-10 17:09 UTC, iBublik commented on app/controllers/admin/badges_controller.rb
> +  before_action :set_badge, only: %i[edit show update destroy]
В других местах подобные коллбеки именуются `find_`. Лучше использовать единообразный нейминг.

2018-05-10 17:09 UTC, iBublik commented on app/views/admin/badges/_form.html.erb
> +    <%= form.select :rule_type, options_for_select([['category', 'category'],
Можно одномерный массив передать, если значение и текст опции совпадают

2018-05-10 17:09 UTC, iBublik commented on config/routes.rb
> +  get '/user_badges', to: 'badges#user_badges'
```ruby
resources :badges, only: :index do
  get :user_badges, on: :collection
end
```

2018-05-10 17:09 UTC, iBublik commented on config/routes.rb
> +  get '/user_badges', to: 'badges#user_badges'
Это конечно не совсем RESTful подход, в результате контроллер распухнет до неприличия. Почитай на досуге - https://habr.com/post/136461/

2018-05-11 09:44 UTC, psylone approved these changes

2018-05-11 09:44 UTC, psylone commented on app/addons/badges_receiver.rb
> +class BadgesReceiver
_addons_ не отражает суть абстракции. В принципе пофигу где она лежит главное чтобы сама абстракция была построена верно, но понятней будет если каталог тоже что-нибудь расскажет о том что за тип у этой абстракции. Например `app/models`, здесь лежат модели. А вот `app/addons` несколько не ясно, что это за дополнения и для чего.

2018-05-11 09:44 UTC, psylone commented on app/controllers/test_passages_controller.rb
> +        @test_passage.update(passed: true)
Лучше сделать отдельный метод модели, например: `@test_passage.complete!`.

2018-06-25 21:25 UTC, merged